name: On Publish Format & Lint Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-and-lint:
    name: Format & Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"  # Cache dependencies for faster runs

      - name: Install dependencies
        run: npm ci  # Faster & safer than "npm install"

      - name: Run Prettier (Format JS, HTML, CSS)
        run: npx prettier --write "**/*.{js,html,css}"

      - name: Run ESLint (Check JS)
        run: npx eslint "**/*.js" --fix || true

      - name: Check for changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No formatting changes needed."
          else
            git commit -m "Auto-formatted code with Prettier & ESLint"
            git push
          fi
